# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #e3e3e3
background              #010101
selection_foreground    #FF8DA1
selection_background    #3d3d3d
background_opacity 0.95
background_blur 15
# Cursor colors
cursor                  #e3e3e3
cursor_text_color       #e3e3e3

# Scrollbar colors
scrollbar_handle_color  #afafaf
scrollbar_track_color   #4a4a4a

# URL color when hovering with mouse
url_color               #008cff

# Kitty window border colors
active_border_color     #262626
inactive_border_color   #6c7086
bell_border_color       #ffffff

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #ffffff
active_tab_background   #8B008B
inactive_tab_foreground #8B008B
inactive_tab_background #8B008B
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #ffffff
mark1_background #ffffff
mark2_foreground #ffffff
mark2_background #ffffff
mark3_foreground #ffffff
mark3_background #ffffff

# The 16 terminal colors

# black
color0 #ffffff
color8 #ffffff

# red
color1 #ffffff
color9 #ffffff

# green
color2  #ffffff
color10 #ffffff

# yellow
color3  #ffffff
color11 #ffffff

# blue
color4  #ffffff
color12 #ffffff

# magenta
color5  #ffffff
color13 #ffffff

# pink
color6  #ffffff
color14 #ffffff

# white
color7  #ffffff
color15 #ffffff
